### ISSUE TITLE
[StartActivity] InterruptedException not handled during connection cancel

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.bcomfy#12]
Bcomfy is crashing if the connection could not be established but the cancel button was pressed.

<pre>
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err: java.lang.InterruptedException
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java8.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:376)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java8.util.concurrent.CompletableFuture.get(CompletableFuture.java:1992)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForData(RSBRemoteService.java:892)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.waitForData(CachedUnitRegistryRemote.java:97)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at org.openbase.bco.registry.remote.Registries.waitForData(Registries.java:148)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.doInBackground(StartActivity.java:299)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.doInBackground(StartActivity.java:292)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-21 13:41:57.255 22665-22693/org.openbase.bco.bcomfy W/System.err:     at java.lang.Thread.run(Thread.java:818)
</pre

**Comment by DivineThreepwood** [comment]
Development of BComfy has been freezed.
