### ISSUE TITLE
[StartActivity] NullPointerException in StartActivity

### ISSUE THREAD

**Issue by jdaberkow** [openbase/bco.bcomfy#20]
The following fatal exception occurs in rare occasions:

```
06-05 21:31:22.531 9342-9342/org.openbase.bco.bcomfy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.openbase.bco.bcomfy, PID: 9342
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity.changeState(StartActivity.java:171)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity.changeState(StartActivity.java:168)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity.lambda$-org_openbase_bco_bcomfy_activityStart_StartActivity_lambda$0(StartActivity.java:75)
                                                                           at org.openbase.bco.bcomfy.activityStart.-$Lambda$39$sbgzPP9gRQrsBBFURTLnUhVZEjw.$m$0(Unknown Source)
                                                                           at org.openbase.bco.bcomfy.activityStart.-$Lambda$39$sbgzPP9gRQrsBBFURTLnUhVZEjw.taskFinishedCallback(Unknown Source)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.onPostExecute(StartActivity.java:312)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.onPostExecute(StartActivity.java:307)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                           at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jdaberkow** [comment]
Still not fixed...

**Comment by DivineThreepwood** [comment]
Development of BComfy has been freezed.
