### ISSUE TITLE
RSB Spread connection lost bug: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.bcomfy#55]
This connection lost happens quite often during the pre study.
Reconnect is only possible after BComfy restart.

<pre>
8-04 15:50:58.600 15357-15357/org.openbase.bco.bcomfy I/InitActivity: Updated shape of location: 1dfd76f9-e21f-47bb-bf6a-df83a6c8db5b
08-04 15:50:58.640 15357-15841/org.openbase.bco.bcomfy W/SpreadWrapperImpl: SpreadException occurred during multicast send of message
                                                                            spread.SpreadException: write(): java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                                at spread.SpreadConnection.multicast(SpreadConnection.java:1978)
                                                                                at rsb.transport.spread.SpreadWrapperImpl.send(SpreadWrapperImpl.java:173)
                                                                                at rsb.transport.spread.RefCountingSpreadWrapper.send(RefCountingSpreadWrapper.java:128)
                                                                                at rsb.transport.spread.SpreadOutConnector.push(SpreadOutConnector.java:257)
                                                                                at rsb.eventprocessing.DefaultOutRouteConfigurator.publishSync(DefaultOutRouteConfigurator.java:91)
                                                                                at rsb.Informer$StateActive.send(Informer.java:186)
                                                                                at rsb.Informer.publish(Informer.java:306)
                                                                                at rsb.patterns.RemoteMethod.call(RemoteMethod.java:171)
                                                                                at rsb.patterns.RemoteServer.callAsyncEvent(RemoteServer.java:407)
                                                                                at rsb.patterns.RemoteServer.callAsyncData(RemoteServer.java:421)
                                                                                at rsb.patterns.RemoteServer.callAsync(RemoteServer.java:164)
                                                                                at org.openbase.jul.extension.rsb.com.RSBSynchronizedRemoteServer.callAsync(RSBSynchronizedRemoteServer.java:135)
                                                                                at org.openbase.jul.extension.rsb.com.RSBRemoteService$2.call(RSBRemoteService.java:666)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
</pre>

**Comment by DivineThreepwood** [comment]
Did no occur again.

**Comment by DivineThreepwood** [comment]
seems to be related:
* https://github.com/open-rsx/rsb-java/issues/30

**Comment by DivineThreepwood** [comment]
closed because bco does not depend anymore on rsb.
