### ISSUE TITLE
Unable to update the locationConfigs in rare occasions

### ISSUE THREAD

**Issue by jdaberkow** [openbase/bco.bcomfy#68]
```
08-23 16:35:29.119 23203-23203/org.openbase.bco.bcomfy E/CoreActivity: Error while updating locationConfig of unit: id: "6db185ba-2a83-4f07-8bdc-25a3cec87f3c"
                                                                       label: "MediaHue"
                                                                       type: DEVICE
                                                                       placement_config {
                                                                         location_id: "81b9efa4-2dc9-432e-b47c-1d73021ff0f3"
                                                                         transformation_frame_id: "MediaHue"
                                                                       }
                                                                       scope {
                                                                         component: "home"
                                                                         component: "living"
                                                                         component: "device"
                                                                         component: "mediahue"
                                                                       }
                                                                       bound_to_unit_host: true
                                                                       meta_config {
                                                                         entry {
                                                                           key: "OPENHAB_BINDING_DEVICE_ID"
                                                                           value: "6"
                                                                         }
                                                                       }
                                                                       enabling_state {
                                                                         value: ENABLED
                                                                       }
                                                                       device_config {
                                                                         serial_number: "DF9598"
                                                                         inventory_state {
                                                                           value: INSTALLED
                                                                           location_id: "81b9efa4-2dc9-432e-b47c-1d73021ff0f3"
                                                                           timestamp {
                                                                             time: 1441016284790
                                                                           }
                                                                           owner_id: ""
                                                                         }
                                                                         device_class_id: "6f661f5b-3906-452a-adb6-a4e5fb94eee4"
                                                                         unit_id: "2ca1b701-cfde-4570-83de-46610e6718fc"
                                                                       }
                                                                       
                                                                       org.openbase.jul.exception.InstantiationException: Could not instantiate ColorableLightSelectorHolder!
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.<init>(AbstractUnitSelectorHolder.java:74)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.ColorableLightSelectorHolder.<init>(ColorableLightSelectorHolder.java:16)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:35)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:30)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder.checkAndAddNewUnit(UiOverlayHolder.java:78)
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity.editApply(CoreActivity.java:515)
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity.lambda$setupGui$3$CoreActivity(CoreActivity.java:300)
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity$$Lambda$3.onClick(Unknown Source)
                                                                           at android.view.View.performClick(View.java:5213)
                                                                           at android.view.View$PerformClick.run(View.java:21172)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.util.concurrent.TimeoutException
                                                                           at java.util.concurrent.FutureTask.get(FutureTask.java:177)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.updatePositionFromRoot(AbstractUnitSelectorHolder.java:197)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.<init>(AbstractUnitSelectorHolder.java:60)
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.ColorableLightSelectorHolder.<init>(ColorableLightSelectorHolder.java:16) 
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:35) 
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:30) 
                                                                           at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder.checkAndAddNewUnit(UiOverlayHolder.java:78) 
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity.editApply(CoreActivity.java:515) 
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity.lambda$setupGui$3$CoreActivity(CoreActivity.java:300) 
                                                                           at org.openbase.bco.bcomfy.activityCore.CoreActivity$$Lambda$3.onClick(Unknown Source) 
                                                                           at android.view.View.performClick(View.java:5213) 
                                                                           at android.view.View$PerformClick.run(View.java:21172) 
                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by jdaberkow** [comment]
Afterwards it is also not possible to fetch the unit transformation until bco gets restarted

```
08-23 16:40:44.641 24040-24289/org.openbase.bco.bcomfy E/fetchNewUnitMapTask: org.openbase.jul.exception.InstantiationException: Could not instantiate ColorableLightSelectorHolder!
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.<init>(AbstractUnitSelectorHolder.java:74)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.ColorableLightSelectorHolder.<init>(ColorableLightSelectorHolder.java:16)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:35)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:30)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.lambda$doInBackground$2$UiOverlayHolder$fetchNewUnitMapTask(UiOverlayHolder.java:153)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask$$Lambda$2.accept(Unknown Source)
                                                                                  at java8.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:220)
                                                                                  at java8.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
                                                                                  at java8.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
                                                                                  at java8.util.ArrayListSpliterator.forEachRemaining(ArrayListSpliterator.java:142)
                                                                                  at java8.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
                                                                                  at java8.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
                                                                                  at java8.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:186)
                                                                                  at java8.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:210)
                                                                                  at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
                                                                                  at java8.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:459)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.doInBackground(UiOverlayHolder.java:150)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.doInBackground(UiOverlayHolder.java:134)
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                               Caused by: java.util.concurrent.TimeoutException
                                                                                  at java.util.concurrent.FutureTask.get(FutureTask.java:177)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.updatePositionFromRoot(AbstractUnitSelectorHolder.java:197)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.AbstractUnitSelectorHolder.<init>(AbstractUnitSelectorHolder.java:60)
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.ColorableLightSelectorHolder.<init>(ColorableLightSelectorHolder.java:16) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:35) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.unitSelectorHolder.SelectorHolderFactory.createUnitSelectorHolder(SelectorHolderFactory.java:30) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.lambda$doInBackground$2$UiOverlayHolder$fetchNewUnitMapTask(UiOverlayHolder.java:153) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask$$Lambda$2.accept(Unknown Source) 
                                                                                  at java8.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:220) 
                                                                                  at java8.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) 
                                                                                  at java8.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) 
                                                                                  at java8.util.ArrayListSpliterator.forEachRemaining(ArrayListSpliterator.java:142) 
                                                                                  at java8.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) 
                                                                                  at java8.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) 
                                                                                  at java8.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:186) 
                                                                                  at java8.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:210) 
                                                                                  at java8.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
                                                                                  at java8.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:459) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.doInBackground(UiOverlayHolder.java:150) 
                                                                                  at org.openbase.bco.bcomfy.activityCore.uiOverlay.UiOverlayHolder$fetchNewUnitMapTask.doInBackground(UiOverlayHolder.java:134) 
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                  at java.lang.Thread.run(Thread.java:818) 
```

**Comment by DivineThreepwood** [comment]
The unit plugins wasn't triggered by consistency modifications.
So the unit transformation was never published which causes into this timeout.

Bugfix is applied to the master branch.
