### ISSUE TITLE
Uncaught exception if no ADF is selected in the SettingsActivity

### ISSUE THREAD

**Issue by jdaberkow** [openbase/bco.bcomfy#83]
https://fabric.io/basecubeone/android/apps/org.openbase.bco.bcomfy/issues/59e63d8861b02d480dbc2d80

```
Fatal Exception: com.google.atap.tangoservice.TangoInvalidException
       at com.google.atap.tangoservice.Tango.throwTangoExceptionIfNeeded(Tango.java:1321)
       at com.google.atap.tangoservice.Tango.connect(Tango.java:694)
       at org.openbase.bco.bcomfy.activityStart.StartActivity.lambda$connectTangoService$4$StartActivity(StartActivity.java:173)
       at org.openbase.bco.bcomfy.activityStart.StartActivity$$Lambda$2.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by DivineThreepwood** [comment]
Development of BComfy has been freezed.
